CREATE USER PacificReef IDENTIFIED BY Hotel_356Oracle2025;
GRANT CONNECT, RESOURCE TO PacificReef;
GRANT CREATE VIEW, CREATE SYNONYM TO PacificReef;

ALTER USER PacificReef QUOTA UNLIMITED ON USERS;
